COMPATIBLE_MACHINE_marsboard-rk3066 = "marsboard-rk3066"
COMPATIBLE_MACHINE_rock2-square = "rock2-square"
COMPATIBLE_MACHINE_radxarock = "radxarock"
COMPATIBLE_MACHINE_firefly-rk3288 = "firefly-rk3288"
COMPATIBLE_MACHINE_vyasa-rk3288 = "vyasa-rk3288"
COMPATIBLE_MACHINE_tinker-board = "tinker-board"
COMPATIBLE_MACHINE_tinker-board-s = "tinker-board-s"
COMPATIBLE_MACHINE_rock-pi-4 = "rock-pi-4"
